### ISSUE TITLE
[Suggestion] use EFF's new wordlist

### ISSUE THREAD

**Issue by Wikinaut** [timoh6/GenPhrase#2]
See https://www.eff.org/deeplinks/2016/07/new-wordlists-random-passphrases

There are three differently flavoured lists available, one long one, and two short ones.

**Comment by timoh6** [comment]
The EFF's long list is actually already in GenPhrase since version 1.1 (with a few modifications). See https://github.com/timoh6/GenPhrase/commit/a890e0552690f72f3d003a9c677a15298e5886b6

**Comment by Wikinaut** [comment]
@timoh6 ty. I actually use the short-list number 1 now.
