### ISSUE TITLE
[Bug] Set of separators issue: I want all generated words separated by a certain character. This does not work as explained.

### ISSUE THREAD

**Issue by Wikinaut** [timoh6/GenPhrase#4]
I wanted all generated words separated by a single dash "-".

First I tried $gen->setSeparators('-'); This threw an error. Readme says, that always a "space" is automatically added to the set, but this appears to be wrong. Then I tried

$gen->setSeparators('- '); // does not work either, see code below.

So the syntax and/or explanation is weird, unclear. Please explain:

#### How can a certain fixed separator like (" ") or ("-") be defined ? The current program version does not work correctly.  

-----
Code:

```
<?php
require 'library/GenPhrase/Loader.php';
$loader = new GenPhrase\Loader();
$loader->register();
$gen = new GenPhrase\Password();
# $gen->disableSeparators(false); // No separator characters are inserted

$gen->disableWordModifier(true); // No words are capitalized or changed to lower case (words are not modified)
$gen->setSeparators('--');
$gen->alwaysUseSeparators(true);
echo $gen->generate(52) . "\n";
```

**Comment by timoh6** [comment]
Currently it is not possible to specify the default separator character (empty space). This seems like a reasonable addition. I'll be working on this.

Also, GenPhrase should throw an exception if separator character string doesn't contain at least two unique characters. I'll be fixing this in master too.

**Comment by Wikinaut** [comment]
With my code (see above), I was unable to have the default space separator present (the I could simply `$string = str_replace( " ", "-", $string );` afterwards.

This did not work when using my wordlist (see code above). Pls. can you assist and modify the code above so that every generated word is separated by a space.

**Comment by timoh6** [comment]
With the most recent commit in master, you can now set just one separator character and it will be used.

`$gen->disableWordModifier(true); // No words are capitalized or changed to lower case (words are not modified)
$gen->setSeparators('-');
$gen->alwaysUseSeparators(true);
echo $gen->generate(52) . "\n";
`
This should now work as expected,

**Comment by timoh6** [comment]
I'm closing this for now, but please re-open if you encounter any problems setting a specific separator character.
