### ISSUE TITLE
Mandate at least one word to begin with uppercase letter?

### ISSUE THREAD

**Issue by twistedpixel** [timoh6/GenPhrase#8]
I'd really like to be able to force at least one word to begin with an uppercase letter but I don't see a way to achieve this currently with the library.

Not a big deal, just thought it might be useful - specially since many systems enforce uppercase letters.

What do you think?

**Comment by timoh6** [comment]
This could be at least somewhat achieved with a custom wordmodifier, which would always toggle the first character of a word to uppercase.

But I'm not sure if it would make more sense to have some deeper control about the passphrase properties (like at least one uppercase letter etc.).

Any suggestions/ideas?

**Comment by timoh6** [comment]
I'll close this for now. Please let me know if some deeper controll of passphrases are needed.

**Comment by twistedpixel** [comment]
Sorry for the late reply. I’m not sure what to suggest really as I’m not sure if mandating certain criteria would screw with your entropy calculation?

I’ve not looked specifically at how you calculate this but I will try to and then make suggestions.

Feel free to keep this issue closed until I have a bit more time to come back to it :)

**Comment by timoh6** [comment]
Yep it's true if words are always toggled to ucfirst, we can't double the dictionary size (regarding entropy calculation) as words would always come out as "Uppercase" instead of either "Uppercase" or "uppercase".

Doing it this way with a custom WordModifier isn't a major problem per se, but it results passphrases to be possible longer than they would be with the default WordModifier. And of course it is somewhat hacky, as passphrases would be then always like "Word1 Word2 Word3 Word4".

**Comment by twistedpixel** [comment]
Ah sorry, I meant only force at least one of the words to be ucfirst(), purely to ensure that the criteria of at least one uppercase letter is met.

When I ran some tests with my config settings, about 1 in 50 came out with no uppercase letters.

I’d suggest a new config option for enforcing at least a single uppercase letter and within the random capitalization function, check for that config option and loop through the array of words to check if any contain an uppercase letter. If not, pick one at random and apply ucfirst().

The reason I was prompted to look into this is that I have an application that picks a password for the user but the password is used across a few linked services, some with more strict password criteria. One of them requires capitalization rather than just calculating an overall entropy score.

What do you think?

**Comment by timoh6** [comment]
Yes this is why having a custom WordModifier to always ucfirst a word is not an ideal solution.

Having deeper control of the passphrase would require a bit more work to be done to GenPhrase internals. But with a quick look it should be doable without "too much work".

I'm thinking something like placing the words into, say, an array and then they could be more easily modified as needed, for example to make sure at least one word is ucfirst.

Separator characters are a bit annoying to handle this way, but maybe just simply putting every word and separator character into a new array element, and then modify that array if needed, and finally implode the array to get final passphrase would get the job done (without adding too much complexity).

This could be added to GenPhrase v1.3.

**Comment by twistedpixel** [comment]
Yep, an array to loop through would be ideal; that's how I'd implement it. If you'd like help with testing or just want to bounce ideas off someone, just give me a shout 👍

**Comment by timoh6** [comment]
Let's go with the array approach. I'll try to take a closer look to this during next weeks. Still need to decide how to handle the actual passphrase modification (and how it impacts the entropy). For now, maybe just add a config param and then based on that setting, modify some element of the array to make sure it starts with an uppercase letter.

Maybe it is simple enough to add an interface, something like modifyPassphraseInterface($passphrase_array) which returns the array with modified elements, and finally GenPhrase implodes the array and returns the passphrase.

Default modifyPassphrase() implementation would just return the array without any modification.  A special implementation would make sure at least one word is ucfirst and if not, ucfirst the first word. (still need to decide should this be hidden behind a config option).

If you have spare time, feel free to send some code :+1:
